# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

title: João Daniel
author:
  name: João Daniel
  email: jd@fores.ee
  github: jdanielnd
  twitter: joaodanielnd
  # pinterest: asd123
  # linkedin: asd123
  # resume: asd123
  bio: Mineiro e estatístico
  email_md5: acd0e265b33eccefa2c089316b5a55f8
  
BASE_PATH: jdanielnd.github.io

categories_path: categories.html
tags_path: tags.html

# mini_magick:
#     thumbnail:
#         source: assets/img/
#         destination: img/photos/thumbnail
#         resize: "100x100"
#     medium:
#         source: assets/img/
#         destination: img/photos/medium
#         resize: "600x400"

